# Generated by Django 3.0.6 on 2020-06-04 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0017_actor_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_auto_20200526_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='UserPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications', models.ManyToManyField(through='login.PublicationInUser', to='asmfa.Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publicationinuser',
            name='userpublication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserPublication'),
        ),
    ]
