# Generated by Django 3.0.6 on 2020-06-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0020_auto_20200604_1150'),
        ('auth', '0011_update_proxy_permissions'),
        ('login', '0004_auto_20200604_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets', models.ManyToManyField(through='login.DatasetInGroup', to='asmfa.Dataset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdataset',
            name='datasets',
        ),
        migrations.RemoveField(
            model_name='userdataset',
            name='user',
        ),
        migrations.DeleteModel(
            name='DatasetInUser',
        ),
        migrations.DeleteModel(
            name='UserDataset',
        ),
        migrations.AddField(
            model_name='datasetingroup',
            name='groupdataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.GroupDataset'),
        ),
    ]
