# Generated by Django 3.0.6 on 2020-06-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0020_auto_20200604_1150'),
        ('login', '0005_auto_20200605_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdataset',
            name='datasets',
        ),
        migrations.AddField(
            model_name='groupdataset',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Dataset'),
        ),
        migrations.DeleteModel(
            name='DatasetInGroup',
        ),
    ]
