# Generated by Django 3.2.18 on 2024-10-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userresetpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResetPassword',
        ),
    ]
