# Generated by Django 3.0.6 on 2021-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
