# Generated by Django 3.0.6 on 2021-06-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_auto_20210525_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='type',
            field=models.CharField(choices=[('dataset', 'dataset'), ('documentation', 'documentation')], default='dataset', max_length=255),
        ),
    ]
