# Generated by Django 4.0.3 on 2022-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_sharedfile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
