# Generated by Django 2.2.8 on 2020-02-04 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nace', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('identifier', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='AdminLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompositeInChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Composite')),
            ],
        ),
        migrations.CreateModel(
            name='FlowChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('route', models.BooleanField()),
                ('collector', models.BooleanField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('trips', models.IntegerField()),
                ('year', models.IntegerField()),
                ('composites', models.ManyToManyField(through='asmfa.CompositeInChain', to='asmfa.Composite')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewc_name', models.CharField(max_length=255)),
                ('ewc_code', models.CharField(max_length=255)),
                ('hazardous', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citekey', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('publicationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.PublicationType')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Material')),
            ],
        ),
        migrations.AddField(
            model_name='flowchain',
            name='materials',
            field=models.ManyToManyField(through='asmfa.MaterialInChain', to='asmfa.Material'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Process'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='products',
            field=models.ManyToManyField(through='asmfa.ProductInChain', to='asmfa.Product'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Waste'),
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_role', models.CharField(max_length=255)),
                ('destination_role', models.CharField(max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='asmfa.Actor')),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='asmfa.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reason', 'Reason'), ('origin', 'Origin'), ('COL', 'Colour'), ('state', 'State'), ('DIM', 'Dimensions'), ('SH', 'Shape'), ('consistency', 'Consistency'), ('COD', 'Codes'), ('m-type', 'Material type'), ('p-type', 'Product type'), ('c-type', 'Composite type'), ('other', 'Other')], max_length=255)),
                ('description', models.TextField(null=True)),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
            ],
        ),
        migrations.AddField(
            model_name='compositeinchain',
            name='flowchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain'),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(null=True)),
                ('mixed', models.BooleanField(null=True)),
                ('direct_use', models.BooleanField(null=True)),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('inhabitants', models.BigIntegerField(default=0)),
                ('adminlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.AdminLevel')),
                ('parent_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Area')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Company'),
        ),
        migrations.AddField(
            model_name='actor',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activitygroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.ActivityGroup'),
        ),
    ]
