# Generated by Django 2.2.8 on 2020-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='composite',
            field=models.BooleanField(null=True),
        ),
    ]
