# Generated by Django 2.2.8 on 2020-03-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='year',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
