# Generated by Django 2.2.7 on 2019-12-02 10:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
