# Generated by Django 2.2.8 on 2020-02-21 11:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0002_classification_composite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='asmfa.Actor')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='asmfa.Actor')),
            ],
        ),
    ]
