# Generated by Django 2.2.8 on 2020-03-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0002_auto_20200311_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowchain',
            old_name='waste',
            new_name='waste06',
        ),
    ]
