# Generated by Django 2.2.8 on 2020-03-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0003_auto_20200316_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='asmfa.Actor')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='asmfa.Actor')),
            ],
        ),
    ]
