# Generated by Django 2.2.7 on 2019-12-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0003_composite_material_process_product_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeInChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Composite')),
            ],
        ),
        migrations.CreateModel(
            name='FlowChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('route', models.BooleanField()),
                ('collector', models.BooleanField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('trips', models.IntegerField()),
                ('year', models.IntegerField()),
                ('composites', models.ManyToManyField(through='asmfa.CompositeInChain', to='asmfa.Composite')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Material')),
            ],
        ),
        migrations.AddField(
            model_name='flowchain',
            name='materials',
            field=models.ManyToManyField(through='asmfa.MaterialInChain', to='asmfa.Material'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Process'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='products',
            field=models.ManyToManyField(through='asmfa.ProductInChain', to='asmfa.Product'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.Waste'),
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_role', models.CharField(max_length=255)),
                ('destination_role', models.CharField(max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='asmfa.Actor')),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='asmfa.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RE', 'Reason'), ('OR', 'Origin'), ('COL', 'Colour'), ('ST', 'State'), ('DIM', 'Dimensions'), ('SH', 'Shape'), ('CON', 'Consistency'), ('COD', 'Codes'), ('MAT', 'Material type'), ('PRO', 'Product type'), ('COMP', 'Composite type')], max_length=255)),
                ('description', models.TextField(null=True)),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
            ],
        ),
        migrations.AddField(
            model_name='compositeinchain',
            name='flowchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain'),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(null=True)),
                ('mixed', models.BooleanField(null=True)),
                ('direct_use', models.BooleanField(null=True)),
                ('flowchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asmfa.FlowChain')),
            ],
        ),
    ]
