# Generated by Django 2.2.8 on 2020-03-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0005_auto_20200317_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowchain',
            name='process',
        ),
        migrations.AddField(
            model_name='actor',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Process'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Activity'),
        ),
    ]
