# Generated by Django 2.2.7 on 2019-12-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0006_publication_publicationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication'),
        ),
        migrations.AddField(
            model_name='area',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Publication'),
        ),
    ]
