# Generated by Django 2.2.8 on 2020-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0006_auto_20200319_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='origin_role',
            field=models.CharField(choices=[('production', 'production'), ('treatment', 'treatment')], max_length=255),
        ),
    ]
