# Generated by Django 2.2.8 on 2020-03-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0007_auto_20200319_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='destination_role',
            field=models.CharField(choices=[('production', 'production'), ('treatment', 'treatment')], max_length=255),
        ),
    ]
