# Generated by Django 2.2.8 on 2019-12-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0007_auto_20191202_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='type',
            new_name='publicationtype',
        ),
    ]
