# Generated by Django 2.2.8 on 2020-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0008_auto_20200319_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='resolution',
            field=models.FloatField(default=0),
        ),
    ]
