# Generated by Django 2.2.8 on 2020-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0008_auto_20191216_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
