# Generated by Django 2.2.8 on 2020-01-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0009_auto_20200127_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='name',
        ),
    ]
