# Generated by Django 2.2.8 on 2020-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0009_adminlevel_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='seq',
            field=models.TextField(null=True),
        ),
    ]
