# Generated by Django 2.2.8 on 2020-04-23 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0010_routing_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('cost', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ways',
                'managed': False,
            },
        ),
    ]
