# Generated by Django 2.2.8 on 2020-05-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0011_ways'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('co2', models.FloatField()),
            ],
        ),
    ]
