# Generated by Django 3.0.6 on 2020-05-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0015_routing_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'processes'},
        ),
    ]
