# Generated by Django 3.0.6 on 2020-05-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0016_auto_20200526_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asmfa.Area'),
        ),
    ]
