# Generated by Django 3.0.6 on 2020-06-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0017_actor_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publicationtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asmfa.PublicationType'),
        ),
    ]
