# Generated by Django 3.0.6 on 2020-06-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0019_auto_20200604_1150'),
        ('login', '0004_auto_20200604_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='dataset',
            name='datasettype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asmfa.DatasetType'),
        ),
        migrations.AddField(
            model_name='actor',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Dataset'),
        ),
        migrations.AddField(
            model_name='area',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Dataset'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Dataset'),
        ),
    ]
