# Generated by Django 3.0.6 on 2020-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0022_processgroup_co2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='nox',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='co2',
            field=models.FloatField(default=0),
        ),
    ]
