# Generated by Django 3.0.6 on 2020-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0023_auto_20200824_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='so2',
            field=models.FloatField(default=0),
        ),
    ]
