# Generated by Django 3.0.6 on 2020-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0024_vehicle_so2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='pm10',
            field=models.FloatField(default=0),
        ),
    ]
