# Generated by Django 3.0.6 on 2021-02-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0026_auto_20210118_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='GNcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='flowchain',
            name='waste06',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.Waste06'),
        ),
        migrations.AddField(
            model_name='flowchain',
            name='gncode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asmfa.GNcode'),
        ),
    ]
