# Generated by Django 3.0.6 on 2021-02-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0028_auto_20210203_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gncode',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
