# Generated by Django 3.0.6 on 2021-02-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0029_auto_20210203_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchain',
            name='collector',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowchain',
            name='route',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
