# Generated by Django 3.2.12 on 2022-03-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0031_alter_activity_id_alter_activitygroup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processgroup',
            name='code',
        ),
    ]
