# Generated by Django 3.2.12 on 2022-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0032_remove_processgroup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste06',
            name='agendas',
            field=models.TextField(default='Onbekend'),
        ),
        migrations.AddField(
            model_name='waste06',
            name='chain_positions',
            field=models.TextField(default='Onbekend'),
        ),
        migrations.AddField(
            model_name='waste06',
            name='industries',
            field=models.TextField(default='Onbekend'),
        ),
        migrations.AddField(
            model_name='waste06',
            name='materials',
            field=models.TextField(default='Onbekend'),
        ),
    ]
