# Generated by Django 3.2.12 on 2022-03-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0033_auto_20220307_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste06',
            old_name='chain_positions',
            new_name='chains',
        ),
        migrations.AddField(
            model_name='waste06',
            name='clean',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='waste06',
            name='mixed',
            field=models.BooleanField(null=True),
        ),
    ]
