# Generated by Django 3.2.12 on 2022-03-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0034_auto_20220314_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositeinchain',
            name='composite',
        ),
        migrations.RemoveField(
            model_name='compositeinchain',
            name='flowchain',
        ),
        migrations.RemoveField(
            model_name='extradescription',
            name='flowchain',
        ),
        migrations.RemoveField(
            model_name='materialinchain',
            name='flowchain',
        ),
        migrations.RemoveField(
            model_name='materialinchain',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productinchain',
            name='flowchain',
        ),
        migrations.RemoveField(
            model_name='productinchain',
            name='product',
        ),
        migrations.RemoveField(
            model_name='flowchain',
            name='composites',
        ),
        migrations.RemoveField(
            model_name='flowchain',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='flowchain',
            name='products',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Composite',
        ),
        migrations.DeleteModel(
            name='CompositeInChain',
        ),
        migrations.DeleteModel(
            name='ExtraDescription',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialInChain',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductInChain',
        ),
    ]
