# Generated by Django 3.2.12 on 2022-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0036_dataset_routing_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grondstof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
