# Generated by Django 3.2.12 on 2022-10-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0038_flowchain_grondstof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.TextField(),
        ),
    ]
