# Generated by Django 3.2.12 on 2022-10-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmfa', '0039_alter_process_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
